# frozen_string_literal: true

require 'fileutils'
require 'yaml'

module JekyllBaserowHeadlessCMS
  # Jekyll Generator that fetches data from Baserow tables
  class Generator < Jekyll::Generator
    safe true
    priority :highest

    def generate(site)
      @site = site
      @config = site.config['baserow'] || {}
      @collections_config = @config['collections'] || {}

      unless @config['enabled'] != false
        Jekyll.logger.info 'BaserowCMS:', 'Plugin disabled in configuration'
        return
      end

      unless ENV['BASEROW_TOKEN']
        Jekyll.logger.info 'BaserowCMS:', 'No BASEROW_TOKEN found, using collections fallback'
        use_all_collections_fallback
        return
      end

      Jekyll.logger.info 'BaserowCMS:', 'Fetching data from Baserow API...'

      begin
        @client = BaserowClient.new(ENV.fetch('BASEROW_TOKEN', nil), base_url: ENV.fetch('BASEROW_API_URL', nil))

        @collections_config.each do |collection_name, collection_config|
          fetch_collection_data(collection_name, collection_config)
        end

        Jekyll.logger.info 'BaserowCMS:', 'All data fetched successfully'
      rescue StandardError => e
        Jekyll.logger.error 'BaserowCMS:', "Error fetching data: #{e.message}"
        Jekyll.logger.warn 'BaserowCMS:', 'Falling back to collections'
        use_all_collections_fallback
      end
    end

    private

    # Fetch data for a single collection
    def fetch_collection_data(collection_name, config)
      env_var = config['table_env']
      data_file = config['data_file']

      table_id = ENV.fetch(env_var, nil)
      if table_id.nil? || table_id.empty? || table_id.start_with?('example_')
        Jekyll.logger.info 'BaserowCMS:', "No #{env_var} found, using fallback for #{collection_name}"
        use_collection_fallback(collection_name, config)
        return
      end

      begin
        baserow_data = @client.query_table(table_id)
        organized_data = DataOrganizers.organize(baserow_data, config)

        if DataOrganizers.data_present?(organized_data)
          data_key = data_file.sub('.yml', '').sub('.yaml', '')
          @site.data[data_key] = organized_data
          create_data_file(organized_data, data_file, collection_name)

          count = organized_data.is_a?(Hash) ? organized_data.size : organized_data.length
          Jekyll.logger.info 'BaserowCMS:', "#{collection_name} fetched (#{count} items)"
        else
          Jekyll.logger.warn 'BaserowCMS:', "No data found for #{collection_name}, using fallback"
          use_collection_fallback(collection_name, config)
        end
      rescue StandardError => e
        Jekyll.logger.error 'BaserowCMS:', "Error fetching #{collection_name}: #{e.message}"
        use_collection_fallback(collection_name, config)
      end
    end

    # Create a YAML data file
    def create_data_file(data, file_name, collection_name)
      data_dir = File.join(@site.source, '_data')
      FileUtils.mkdir_p(data_dir)

      data_file = File.join(data_dir, file_name)
      new_content = data.to_yaml

      # Skip if content unchanged
      if File.exist?(data_file)
        existing_content = File.read(data_file)
        yaml_start = existing_content.index("---\n")
        if yaml_start
          existing_yaml = existing_content[yaml_start..]
          if existing_yaml.strip == new_content.strip
            Jekyll.logger.info 'BaserowCMS:', "#{collection_name} data unchanged, skipping"
            return
          end
        end
      end

      File.open(data_file, 'w') do |file|
        file.write("# #{collection_name.capitalize} data imported from Baserow\n")
        file.write("# Auto-generated by jekyll-baserow-headless-cms - Do not edit manually\n")
        file.write("# Last updated: #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        file.write(new_content)
      end

      Jekyll.logger.info 'BaserowCMS:', "#{collection_name} written to _data/#{file_name}"
    end

    # Use fallback for all collections
    def use_all_collections_fallback
      @collections_config.each do |collection_name, config|
        use_collection_fallback(collection_name, config)
      end
    end

    # Use Jekyll collections as fallback
    def use_collection_fallback(collection_name, config)
      Jekyll.logger.info 'BaserowCMS:', "Using fallback for #{collection_name}"

      data_file = config['data_file']
      data_key = data_file.sub('.yml', '').sub('.yaml', '')
      fields_config = config['fields'] || []

      # Convert Jekyll collection to Baserow-like row format
      mock_data = { 'results' => [] }

      @site.collections[collection_name]&.docs&.each_with_index do |doc, index|
        row = { 'id' => "collection_#{index}" }
        row.merge!(convert_doc_to_fields(doc.data, fields_config))
        mock_data['results'] << row
      end

      organized_data = DataOrganizers.organize(mock_data, config)
      @site.data[data_key] = organized_data
      create_data_file(organized_data, data_file, collection_name)

      count = organized_data.is_a?(Hash) ? organized_data.size : organized_data.length
      Jekyll.logger.info 'BaserowCMS:', "#{collection_name} fallback applied (#{count} items)"
    end

    # Convert Jekyll document data to Baserow-like row fields
    def convert_doc_to_fields(data, fields_config)
      fields = {}

      fields_config.each do |field_config|
        field_name = field_config['name']
        field_type = field_config['type']
        field_key = field_config['key'] || FieldExtractors.normalize_key(field_name)

        value = data[field_key] || data[field_name.downcase] || data[field_name]
        next if value.nil?

        fields[field_name] = convert_value_to_baserow_field(value, field_type)
      end

      fields
    end

    # Convert a value to a Baserow field value shape
    def convert_value_to_baserow_field(value, field_type)
      case field_type
      when 'number', 'rating', 'count'
        value.to_i
      when 'boolean'
        !!value
      when 'single_select'
        { 'id' => nil, 'value' => value.to_s, 'color' => nil }
      when 'multi_select'
        items = value.is_a?(Array) ? value : [value]
        items.map { |v| { 'id' => nil, 'value' => v.to_s, 'color' => nil } }
      else
        value.to_s
      end
    end
  end
end
